const store = [
  {
    No: 2,
    Name: "Borough",
    Address: "302 Borough High Street, Borough, London SE1 1JJ",
    Link: "https://deliveroo.co.uk/menu/london/borough/asia-villa-borough-high-street",
    tel: "02074075301",
    Opening: "10.00AM",
    Closing: "11.00PM",
  },
  {
    No: 1,
    Name: "Upton Town",
    Address: "409 Katherine Road, London, E7 8LT",
    Link: "https://deliveroo.co.uk/menu/London/upton/asia-villa-upt",
    tel: "02085524488",
    Opening: "12.00PM",
    Closing: "10.00PM",
  },
  {
    No: 3,
    Name: "Canary Wharf",
    Address: "267 East India Dock Road, Poplar, London, E14 0EG",
    Link: "https://deliveroo.co.uk/menu/London/langdon-park/asia-villa-london",
    tel: "02036892619",
    Opening: "10.00AM",
    Closing: "12.00AM",
  },
  {
    No: 4,
    Name: "Romford",
    Address: "19 Victoria Road, Romford RM1 2JT",
    Link: "https://deliveroo.co.uk/menu/London/hylands/asia-villa-romford",
    tel: "01708500705",
    Opening: "10.00AM",
    Closing: "11.00PM",
  },
  {
    No: 6,
    Name: "Wood Green",
    Address: "462 Lordship Lane Wood Green, London N17 7QY",
    Link: "https://deliveroo.co.uk/menu/London/downhills-park-tower-garden-estate/asia-villa",
    tel: "02088856176",
    Opening: "10.00AM",
    Closing: "11.00PM",
  },
  {
    No: 5,
    Name: "Angel",
    Address: "379 St John St, London EC1V 4LD",
    Link: "https://deliveroo.co.uk/menu/london/angel/asia-villa-st-john-street",
    tel: "02078372880",
    Opening: "12.00PM",
    Closing: "10.00PM",
  },
];
export default store;
