const data = [
  {
    id: 1,
    title: "Edamame (Vegan) 🌱",
    description: "Green soya bean pods seasoned with sea-salt.",
    price: "5.50",
    category: "APPETISER 🥢",
    image: "/Photos/Edamame.jpeg",
    vegan: "true",
    contains: "Soya",
    available: "true",
  },
  {
    id: 2,
    title: "Vegetable Spring Roll (Vegan) 4pcs 🌱",
    description: "Crispy fried spring rolls served with sweet chilli sauce.",
    price: "5.50",
    category: "APPETISER 🥢",
    image: "/Photos/Vegetable_Spring_Roll.jpeg",
    vegan: "true",
    contains: "Sesame, Soya, Gluten",
    available: "true",
  },
  {
    id: 3,
    title: "Salt + Pepper Tofu (Vegan) 🌱",
    description:
      "Deep fried tofu tossed in salt, pepper, chilli and spring onions.",
    price: "5.50",
    category: "APPETISER 🥢",
    image: "/Photos/Salt&Pepper_Calamri.jpeg",
    vegan: "true",
    contains: "Soya",
    available: "true",
  },
  {
    id: 4,
    title: "Vegetable Gyoza (Vegan) 5pcs",
    description:
      "Deep fried dumplings with plenty of vegetables and well-balanced nutrition with soybean protein. Served with vinegar, ginger, soy and chilli dipping sauce.",
    price: "5.50",
    category: "APPETISER 🥢",
    image: "/Photos/Vegetable_Gyoza.jpeg",
    vegan: "true",
    contains: "Soya, Gluten",
    available: "true",
  },
  {
    id: 5,
    title: "Chicken Gyoza (5pcs)",
    description:
      "Deep fried chicken dumplings served with vinegar, ginger, soy and chilli dipping sauce.",
    price: "5.50",
    category: "APPETISER 🥢",
    image: "/Photos/Chicken_Goyza.jpeg",
    vegan: "false",
    contains: "Gluten, Soya, Sesame",
    available: "true",
  },
  {
    id: 6,
    title: "Chicken Satay (4pcs)",
    description:
      "Thai satay marinated pieces of chicken cooked over a chargrill and served on skewers with peanut dipping sauce.",
    price: "5.50",
    category: "APPETISER 🥢",
    image: "/Photos/Chicken_Satay.jpeg",
    vegan: "false",
    contains: "Soya, Gluten, Milk",
    available: "true",
  },
  {
    id: 7,
    title: "Salt + Pepper Calamari",
    description:
      "Deep fried calamari tossed in salt, pepper, chilli and spring onions.",
    price: "6.99",
    category: "APPETISER 🥢",
    image: "/Photos/Salt&Pepper_Calamri.jpeg",
    vegan: "false",
    contains: "Molluscs, Eggs, Soya",
    available: "true",
  },
  {
    id: 8,
    title: "Prawn Toast (5pcs)",
    description:
      "Crispy fried minced prawn and sesame toast served with sweet chilli sauce.",
    price: "5.95",
    category: "APPETISER 🥢",
    image: "/Photos/Prawn_Toast.jpeg",
    vegan: "false",
    contains: "Sesame, Soya, Gluten",
    available: "true",
  },
  {
    id: 9,
    title: "Prawn Tempura (5pcs)",
    description:
      "Deep fried tail on king prawns enrobed in a tempura batter. Served with sweet chilli sauce.",
    price: "5.80",
    category: "APPETISER 🥢",
    image: "/Photos/Prawn_Tempura.jpeg",
    vegan: "false",
    contains: "Crustaceans, Gluten",
    available: "true",
  },
  {
    id: 10,
    title: "Duck Spring Roll (5pcs)",
    description:
      "Crispy spring roll filled with five spice roasted duck and served with Hoisin sauce.",
    price: "6.00",
    category: "APPETISER 🥢",
    image: "/Photos/Duck_Spring_Roll.jpeg",
    vegan: "false",
    contains: " Gluten, Soya, Sesame",
    available: "true",
  },
  {
    id: 11,
    title: "Thai Chicken Wings",
    description:
      "Deep fried chicken wings seasoned with garlic, five spice, chilli, onions, spring onions, salt, pepper and herbs.",
    price: "5.50",
    category: "APPETISER 🥢",
    image: "/Photos/Thai_Chicken_Wings.jpeg",
    vegan: "false",
    contains: " Gluten, Milk, Soya, Sesame",
    available: "true",
  },
  {
    id: 12,
    title: "Fish Cake (5pcs)",
    description:
      "Thai style mildly spicy and deep fried cake served with sweet chilli sauce.",
    price: "5.50",
    category: "APPETISER 🥢",
    image: "/Photos/Fish_Cake.jpeg",
    vegan: "false",
    contains: "Gluten, Fish, Soya",
    available: "true",
  },
  {
    id: 13,
    title: "Wasabi Peas (Vegan) Spicy 🌱",
    description:
      "Great as a crunchy bite; green peas coated with wasabi . Mixture of spicy, salty and sweet flavour.",
    price: "3.50",
    category: "QUICK BITE",
    image: "/Photos/Wasabi_Peas.jpeg",
    vegan: "true",
    contains: "Mustard",
    available: "true",
  },
  {
    id: 14,
    title: "Prawn Cracker",
    description:
      "Delight in the irresistible crunch of our handcrafted prawn crackers. Made from a secret blend of premium prawns.",
    price: "3.70",
    category: "QUICK BITE",
    image: "/Photos/Prawn_Cracker.jpeg",
    vegan: "false",
    contains: "Crustaceans, Soya",
    available: "true",
  },
  {
    id: 15,
    title: "Thai Crunch Peanut Dressing Salad 🌶 🌶",
    description:
      "Healthy & packed with lots of flavor. Cucumber, edamame beans, shredded carrot, lettuce, green & red peppers all mixed with peanut dressing and soy sauce.",
    price: "8.50",
    category: "SALAD",
    choices: "Chicken,Tofu vegan 🌱",
    image: "/Photos/Thai_Crunch_Peanut_Dressing_Salad.jpeg",
    vegan: "true",
    contains: "Soya, Peanuts",
    available: "true",
  },
  {
    id: 16,
    title: "Seaweed Salad (Vegan)🌱",
    description:
      "A unique briny & umami flavoured seaweed salad along with a degree of sweetness . Mixed with sesame seeds.",
    price: "3.50",
    category: "SALAD",
    image: "/Photos/Seaweed_Salad.jpeg",
    vegan: "true",
    contains: "Sesame",
    available: "true",
  },
  {
    id: 17,
    title: "Tom Yum (Medium) 450 Ml",
    description:
      "Medium spicy and sour Thai style broth with cabbage, mushrooms, coriander and tomatoes.",
    price: "5.50",
    category: "SOUP",
    choices: "Chicken,Prawn,Tofu vegan 🌱",
    image: "/Photos/Tom_Yum_(Medium).jpeg",
    vegan: "true",
    contains: "Soya",
    available: "true",
  },
  {
    id: 18,
    title: "Tom Kha (Mild) 450 Ml",
    description:
      "Mild spicy & sour Thai style broth with coconut milk, cabbage , coriander and mushrooms.",
    price: "5.80",
    category: "SOUP",
    choices: "Chicken,Prawn,Tofu vegan 🌱",
    image: "/Photos/Tom_Kha_(Mild).jpeg",
    vegan: "true",
    contains: "Soya",
    available: "true",
  },
  {
    id: 19,
    title: "Miso (450 Ml)",
    description:
      "Traditionally made dashi (fish stock/ vegan stock) with white miso, tofu, seaweed, and spring onions Vegan option on request 🌱",
    price: "3.50",
    category: "SOUP",
    image: "/Photos/Miso.jpeg",
    vegan: "true",
    contains: "Soya",
    available: "true",
  },
  {
    id: 20,
    title: "Ramen (Japanese Favourite Soup)",
    description:
      "Japanese style soup served with boiled egg ,ramen noodles, fish cake, dashi, white miso, seaweed, spring onions, dried mushroom and fish sauce.",
    price: "8.99",
    category: "BIG BOWL SOUP",
    choices: "Tempura Prawn,Roast Duck,Crispy Chicken,Tofu vegan 🌱",
    image: "/Photos/Ramen.jpeg",
    vegan: "true",
    contains: "Soya",
    available: "true",
  },
  {
    id: 21,
    title: "Tom Yum Vermicelli (Medium)🌶",
    description:
      "Medium spicy and sour Thai style broth served with thin rice vermicelli noodles, tomatoes, mushroom, coriander, spring onions, beansprout and shredded carrot.",
    price: "8.99",
    category: "BIG BOWL SOUP",
    choices: "Chicken,Prawn,Tofu vegan 🌱",
    image: "/Photos/Tom_Yum_Vermicelli.jpeg",
    vegan: "true",
    contains: "Soya",
    available: "true",
  },
  {
    id: 22,
    title: "Pad Thai (Thai Favourite) Mild 🌶",
    description:
      "Mildly spicy wok fried flat rice noodles with egg, garlic, fish sauce, lime wedge, spring onions, carrot, beansprouts and crushed peanuts on the side.",
    price: "8.99",
    category: "WOK NOODLES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu with egg,Tofu Vegan 🌱",
    image: "/Photos/Pad_Thai_(Thai_Favourite)_Mild.jpeg",
    vegan: "true",
    contains: "Peanuts, Eggs, Fish",
    available: "true",
  },
  {
    id: 23,
    title: "Pad See Ew (Medium)",
    description:
      "Wok fried flat rice noodle with egg, garlic, dark soy sauce, oyster sauce, sesame oil, siracha sauce, pepper powder, carrots, broccoli, cabbage, red & green peppers with a medium level of spice.",
    price: "8.99",
    category: "WOK NOODLES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu with egg,Tofu Vegan 🌱",
    image: "/Photos/Tom_Kha_(Mild).jpeg",
    vegan: "true",
    contains: "Eggs, Gluten, Molluscs, Sesame, Soya",
    available: "true",
  },
  {
    id: 24,
    title: "Pad Kee Mao (Spicy) 🌶 🌶",
    description:
      "Spicy wok fried flat rice noodle with egg, garlic, fish sauce, dark soy, red &green peppers, mushroom, aubergine, cabbage, green beans, mint/ basil, chillies, lemon juice and finely chopped lemongrass.",
    price: "8.99",
    category: "WOK NOODLES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu with egg,Tofu Vegan 🌱",
    image: "/Photos/Pad_Kee_Mao_(Spicy).jpeg",
    vegan: "true",
    contains: "Soya, Gluten, Fish, Eggs",
    available: "true",
  },
  {
    id: 25,
    title: "Chilli Yaki Udon (Spicy) 🌶🌶🌶",
    description:
      "Spicy wok fried udon noodle with egg, fish sauce, dark soy, sesame oil, carrot, beansprouts, cabbage, peppers, spring onion, and crispy prawn chilli paste.",
    price: "9.50",
    category: "WOK NOODLES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu with egg,Tofu Vegan 🌱",
    image: "/Photos/Chilli_Yaki_Udon_(Spicy).jpeg",
    vegan: "true",
    contains: "Soya, Sesame, Gluten, Fish, Eggs",
    available: "true",
  },
  {
    id: 26,
    title: "Singapore Noodle (Mild)",
    description:
      "Stir fried rice vermicelli noodle mildly spiced with curry powder, egg, soy sauce, garlic, peppers, cabbage, onions, carrot, beansprout and spring onions.",
    price: "8.99",
    category: "WOK NOODLES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu with egg,Tofu Vegan 🌱",
    image: "/Photos/Singapore_Noodle.jpeg",
    vegan: "true",
    contains: " Eggs, Gluten, Sesame, Milk, Soya",
    available: "true",
  },
  {
    id: 27,
    title: "Scissor (Burmese Favourite) Spicy 🌶🌶🌶",
    description:
      "Spicy wok fried flat rice noodle with egg, garlic, fish sauce, prawn chilli, vinegar, carrot, beansprout, cabbage, peppers, spring onion, and chilli bean paste.",
    price: "8.99",
    category: "WOK NOODLES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu with egg,Tofu Vegan 🌱",
    image: "/Photos/Scissor_(Burmese_Favourite).jpeg",
    vegan: "true",
    contains: "Soya, Gluten, Fish, Eggs",
    available: "true",
  },
  {
    id: 28,
    title: "Yakisoba (Mild)",
    description:
      "Wok fried yellow noodle with eggs, ginger, garlic, onions, dashi, yakisoba sauce, carrot, beansprouts, cabbage, peppers and spring onion.",
    price: "8.99",
    category: "WOK NOODLES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu with egg,Tofu Vegan 🌱",
    image: "/Photos/Yakisoba.jpeg",
    vegan: "true",
    contains: " Eggs, Gluten, Soya",
    available: "true",
  },
  {
    id: 29,
    title: "Chow Mein (Mild)",
    description:
      "Wok-fried yellow noodle with egg, garlic, onions, spring onions, cabbage, shredded carrots, beansprouts, soy sauce and sesame oil.",
    price: "8.99",
    category: "WOK NOODLES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu with egg,Tofu Vegan 🌱",
    image: "/Photos/Chow_Mein_(Mild).jpeg",
    vegan: "true",
    contains: "Eggs, Gluten, Milk, Sesame, Soya",
    available: "true",
  },
  {
    id: 30,
    title: "Nasi Goreng (Medium) 🌶",
    description:
      "Medium spicy Malaysian fried rice cooked with egg, shrimp paste, ginger, garlic, soy sauce, carrots and green beans. Served with crispy shallot & fried egg on the top.",
    price: "8.99",
    category: "RICE DISHES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu(With egg)🥚",
    image: "/Photos/Nasi_Goreng_(Medium).jpeg",
    vegan: "false",
    contains: "Crustaceans, Soya, Sesame, Gluten, Eggs",
    available: "true",
  },
  {
    id: 31,
    title: "Special Fried Rice (Mild)",
    description:
      "Fried rice with egg, garlic, mixed vegetables and soy sauce. Served with crispy shallot & fried egg on the top.",
    price: "8.99",
    category: "RICE DISHES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu(With egg)🥚,Tofu Vegan 🌱",
    image: "/Photos/Special_Fried_Rice_(Mild).jpeg",
    vegan: "true",
    contains: "Soya, Gluten, Eggs, Milk",
    available: "true",
  },
  {
    id: 32,
    title: "Katsu Curry (Mild)",
    description:
      "Mildly spicy Japanese curry sauce with bit of carrots and onions. Served with rice.",
    price: "10.00",
    category: "RICE DISHES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu Vegan 🌱",
    image: "/Photos/Katsu_Curry_(Mild).jpeg",
    vegan: "true",
    contains: " Gluten, Soya",
    available: "true",
  },
  {
    id: 33,
    title: "Green Curry (Spicy) 🌶🌶🌶",
    description:
      "Spicy Thai green curry, coconut milk with bamboo shoots, aubergine, red & green peppers and fine beans. Served with rice.",
    price: "10.00",
    category: "RICE DISHES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu Vegan 🌱",
    image: "/Photos/Green_Curry_(Spicy).jpeg",
    vegan: "true",
    contains: "Crustaceans, Soya, Sesame, Gluten, Eggs",
    available: "true",
  },
  {
    id: 34,
    title: "Red Curry (Spicy) 🌶🌶🌶",
    description:
      "Spicy Thai red curry, coconut milk with bamboo shoots, aubergine, red & green peppers and fine beans. Served with rice.",
    price: "10.00",
    category: "RICE DISHES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu(With egg)🥚",
    image: "/Photos/Red_Curry_(Spicy).jpeg",
    vegan: "false",
    contains: "Crustaceans, Soya, Sesame, Gluten, Eggs",
    available: "true",
  },
  {
    id: 35,
    title: "Red Curry Duck (Spicy) 🌶🌶🌶",
    description:
      "Spicy Thai red curry, coconut milk with red & green peppers, pineapple and roasted duck. Served with rice.",
    price: "10.00",
    category: "RICE DISHES (MAIN)",
    choices: "Duck",
    image: "/Photos/Red_Curry_Duck_(Spicy).jpeg",
    vegan: "false",
    contains: "Crustaceans, Soya, Sesame, Gluten, Eggs",
    available: "true",
  },
  {
    id: 36,
    title: "Massaman Curry (Medium) 🌶",
    description:
      "Medium spicy Thai massaman curry, coconut milk with red & green peppers, onions, tamarind and potato. Served with rice & crushed peanuts on the side",
    price: "10.00",
    category: "RICE DISHES (MAIN)",
    choices: "Chicken,Prawn,Beef,Tofu Vegan 🌱",
    image: "/Photos/Massaman_Curry_(Medium).jpeg",
    vegan: "false",
    contains: "Crustaceans, Soya, Sesame, Gluten, Eggs",
    available: "true",
  },
  {
    id: 37,
    title: "Sweet And Sour (Served With Rice)",
    description:
      "Cooked with vegetables including broccoli, carrot, onion, red & green peppers, pineapple, spring onions and tomatoes. (Chicken and prawns are coated in the batter of egg & potato starch)",
    price: "10.00",
    category: "RICE DISHES (MAIN)",
    choices: "Chicken,Prawn,Tofu Vegan 🌱",
    image: "/Photos/Sweet_And_Sour_(Served_With_Rice).jpeg",
    vegan: "true",
    contains: "Crustaceans, Soya, Sesame, Gluten, Eggs",
    available: "true",
  },
  {
    id: 38,
    title: "Chicken Teriyaki (Served With Rice)",
    description:
      "Tender chicken grilled and cooked in sweet teriyaki sauce with cabbage, carrots, edamame beans and sesame seeds. Served with rice.",
    price: "10.00",
    category: "RICE DISHES (MAIN)",
    choices: " Chicken",
    image: "/Photos/Chicken_Teriyaki_(Served_With_Rice).jpeg",
    vegan: "false",
    contains: " Soya, Sesame, Gluten",
    available: "true",
  },
  {
    id: 39,
    title: "Boiled Rice 🌱",
    description: "",
    price: "3.50",
    category: "SIDE DISHES",
    image: "/Photos/Boiled_Rice.jpeg",
    vegan: "true",
    contains: "Gluten",
    available: "true",
  },

  {
    id: 40,
    title: "Coconut Rice 🌱",
    description:
      "Boiled rice with lightly sweet coconut milk and touch of salt.",
    price: "4.50",
    category: "SIDE DISHES",
    image: "/Photos/Coconut_Rice.jpeg",
    vegan: "true",
    contains: "Gluten",
    available: "true",
  },
  {
    id: 41,
    title: "Egg Fried Rice",
    description:
      "Fried rice with egg, soy sauce, garlic, spring onions and fried onions on top.",
    price: "4.50",
    category: "SIDE DISHES",
    image: "/Photos/Egg_Fried_Rice.jpeg",
    vegan: "false",
    contains: "Soya, Eggs, Milk, Gluten",
    available: "true",
  },
  {
    id: 42,
    title: "Mix Vegetable (Vegetarian)",
    description:
      "Stir fried mixed vegetables normally red & green peppers, broccoli, carrots, green beans, mushroom, cabbage, tomato. beansprouts, garlic, onions, spring onions, sesame oil and soy sauce.",
    price: "5.50",
    category: "SIDE DISHES",
    image: "/Photos/Mix_Vegetable_(Vegetarian).jpeg",
    vegan: "true",
    contains: "Gluten, Milk, Soya, Sesame",
    available: "true",
  },
  {
    id: 43,
    title: "Stir Fried Broccoli With Oyster Sauce",
    description:
      "Stir fried broccoli, carrots, garlic, onions, spring onions, oyster sauce, soy sauce and sesame oil.",
    price: "6.50",
    category: "SIDE DISHES",
    image: "/Photos/Stir_Fried_Broccoli_With_Oyster_Sauce.jpeg",
    vegan: "true",
    contains: "Soya, Molluscs, Sesame, Milk, Gluten",
    available: "true",
  },
  {
    id: 44,
    title: "Curry Sauce (Vegan)🌱",
    description: "Katsu curry sauce with bit of onions and carrots.",
    price: "4.50",
    category: "SIDE DISHES",
    image: "/Photos/Curry_Sauce_(Vegan).jpeg",
    vegan: "true",
    contains: " Gluten, Soya",
    available: "true",
  },
  {
    id: 45,
    title: "Japanese Dorayaki Chocolate",
    description:
      "Traditional Japanese style thick, spongy amd sweet pancakes sandwiched with a sweet chocolate cream filling",
    price: "3.50",
    category: "DESSERTS",
    image: "/Photos/Japanese_Dorayaki_Chocolate.jpeg",
    vegan: "false",
    contains: "Milk, Gluten, Eggs, Soya",
    available: "true",
  },
  {
    id: 46,
    title: "White Chocolate Pyramid",
    description:
      "Success biscuit, white chocolate mouse caramel cream and white chocolate icing.",
    price: "4.50",
    category: "DESSERTS",
    image: "/Photos/White_Chocolate_Pyramid.jpeg",
    vegan: "false",
    contains: "Milk, Nuts, Gluten, Eggs, Fish",
    available: "true",
  },
  {
    id: 47,
    title: "Mango + Passion Fruit ( Thai Favourite)",
    description:
      "Mango torte on a sponge base, finished with a passion fruit glaze.",
    price: "4.50",
    category: "DESSERTS",
    image: "/Photos/Mango_Passion_Fruit_(Thai_Favourite).jpeg",
    vegan: "false",
    contains: "Eggs, Gluten, Milk",
    available: "true",
  },
  {
    id: 48,
    title: "Vanilla Ice-Cream Mochi (2pcs)",
    description:
      "Japanese style soft, slightly chewy and sweet rice dough filled with vanilla ice cream in the center.",
    price: "3.50",
    category: "DESSERTS",
    image: "/Photos/Vanilla_Ice_Cream_Mochi_(2pcs).jpeg",
    vegan: "false",
    contains: "Soya, Milk",
    available: "true",
  },
  {
    id: 49,
    title: "Strawberry Cheesecake Mochi (2 Pcs)",
    description:
      "Japanese style soft, slightly chewy and sweet rice dough filled with strawberry cheese ice cream in the center.",
    price: "3.50",
    category: "DESSERTS",
    image: "/Photos/Strawberry_Cheesecake_Mochi.jpeg",
    vegan: "false",
    contains: "Soya, Milk",
    available: "true",
  },
  {
    id: 50,
    title: "Chocolate Mochi (2 Pcs)",
    description:
      "Japanese style soft, slightly chewy and sweet rice dough filled with chocolate ice cream in the center.",
    price: "3.50",
    category: "DESSERTS",
    image: "/Photos/Chocolate_Mochi.jpeg",
    vegan: "false",
    contains: " Milk,Soya",
    available: "true",
  },
  {
    id: 51,
    title: "San Pellegrino Blood Orange",
    description: "330ml can",
    price: "1.50",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/San_Pellegrino_Blood_Orange.jpeg",
    available: "true",
  },
  {
    id: 52,
    title: "San Pellegrino Lemon",
    description: "330ml can",
    price: "1.50",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/San_Pellegrino_Lemon.jpeg",
    available: "true",
  },
  {
    id: 53,
    title: "Coca Cola Can",
    description: "330ml can",
    price: "1.50",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/Coca_Cola_Can.jpeg",
    available: "true",
  },
  {
    id: 54,
    title: "Diet Coke Can",
    description: "330ml can",
    price: "1.50",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/Coca_Cola_Can.jpeg",
    available: "true",
  },
  {
    id: 55,
    title: "Fanta Orange Can",
    description: "330ml can",
    price: "1.50",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/Coca_Cola_Can.jpeg",
    available: "true",
  },
  {
    id: 56,
    title: "7up Can",
    description: "330ml can",
    price: "1.50",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/Coca_Cola_Can.jpeg",
    available: "true",
  },
  {
    id: 57,
    title: "7up Light Can",
    description: "330ml can",
    price: "1.50",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/Coca_Cola_Can.jpeg",
    available: "true",
  },
  {
    id: 58,
    title: "Still Water",
    description: "330ml can",
    price: "1.50",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/Still_Water.jpeg",
    available: "true",
  },
  {
    id: 59,
    title: "Sparkling Water",
    description: "330ml can",
    price: "1.50",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/Sparkling_Water.jpeg",
    available: "true",
  },
  {
    id: 60,
    title: "Aloe Vera 500 Ml",
    description: "500 ml Bottle",
    price: "2.00",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/Aloe_Vera_500_Ml.jpeg",
    available: "true",
  },
  {
    id: 61,
    title: "Apple Juice ( 500 Ml)",
    description: "500ml can",
    price: "2.50",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/San_Pellegrino_Blood_Orange.jpeg",
    available: "true",
  },
  {
    id: 62,
    title: "Orange Juice (500 Ml)",
    description: "500ml can",
    price: "2.50",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/San_Pellegrino_Blood_Orange.jpeg",
    available: "true",
  },
  {
    id: 63,
    title: "Mango Juice (500 Ml)",
    description: "500ml can",
    price: "2.50",
    category: "SOFT DRINKS & JUICES",
    image: "/Photos/San_Pellegrino_Blood_Orange.jpeg",
    available: "true",
  },
  {
    id: 64,
    title: "Jasmine Tea",
    description: "Hot Drinks",
    price: "2.00",
    category: "HOT DRINKS",
    image: "/Photos/Jasmine_Tea.jpeg",
    available: "true",
  },
  {
    id: 65,
    title: "Green Tea",
    description: "Hot Drinks",
    price: "2.00",
    category: "HOT DRINKS",
    image: "/Photos/Green_Tea.jpeg",
    available: "true",
  },
  {
    id: 66,
    title: "Satay Peanut Sauce",
    description: "20Z",
    price: "1.00",
    category: "SAUCES",
    contains: "Soya, Gluten, Peanuts",
    available: "true",
  },
  {
    id: 67,
    title: "Sweet Chilli Sauce",
    description: "20Z",
    price: "1.00",
    category: "SAUCES",
    available: "true",
  },
  {
    id: 68,
    title: "Chilli Oil",
    description: "20Z",
    price: "1.00",
    category: "SAUCES",
    available: "true",
  },
  {
    id: 69,
    title: "Crushed Peanuts",
    description: "20Z",
    price: "1.00",
    category: "SAUCES",
    contains: "Soya, Peanuts",
    available: "true",
  },
  {
    id: 70,
    title: "Soy Sauce",
    description: "20Z",
    price: "1.00",
    category: "SAUCES",
    contains: "Soya",
    available: "true",
  },
  {
    id: 71,
    title: "Hoisin Sauce",
    description: "20Z",
    price: "1.00",
    category: "SAUCES",
    available: "true",
  },
];
export default data;
